[build]
builder = "NIXPACKS"
buildCommand = "npx prisma generate && npm run build"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/api/healthz"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
